name: S-Economy
version: '1.2.3'
main: dev.losterixx.sEconomy.Main
api-version: '1.21'
authors: [ Losterixx ]
description: Just a simple and lightweight economy system.
load: STARTUP
depend:
  - Vault
softdepend:
  - S-Core
  - LuckPerms
permissions:
  "s-economy.admin":
    description: Allows the player to use the main command of S-Economy.
    default: op
  "s-economy.command.balance.self":
    description: Allows the player to check their own balance.
    default: true
  "s-economy.command.balance.other":
    description: Allows the player to check the balance of other players.
    default: op
  "s-economy.command.pay":
    description: Allows the player to pay other players.
    default: op
  "s-economy.command.pay.all":
    description: Allows the player to pay all players.
    default: op
  "s-economy.command.eco.give":
    description: Allows the player to give money to other players.
    default: op
  "s-economy.command.eco.take":
    description: Allows the player to take money from other players.
    default: op
  "s-economy.command.eco.set":
    description: Allows the player to set the balance of other players.
    default: op
  "s-economy.command.eco.reset":
    description: Allows the player to reset the balance of other players.
    default: op
  "s-economy.command.eco.check":
    description: Allows the player to check the balance of other players.
    default: op
  "s-economy.command.balancetop":
    description: Allows the player to view the top balance of all players.
    default: op
  "s-economy.exempt.balancetop":
    description: Exempts the player from appearing in the balance top.
    default: op
